/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SuppliesRouteImport } from './routes/supplies'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as VisitorsRouteImport } from './routes/visitors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesRoute = SuppliesRouteImport.update({
  id: '/supplies',
  path: '/supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/leave': typeof LeaveRoute
  '/meetings': typeof MeetingsRoute
  '/more': typeof MoreRoute
  '/reports': typeof ReportsRoute
  '/supplies': typeof SuppliesRoute
  '/tasks': typeof TasksRoute
  '/visitors': typeof VisitorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/leave': typeof LeaveRoute
  '/meetings': typeof MeetingsRoute
  '/more': typeof MoreRoute
  '/reports': typeof ReportsRoute
  '/supplies': typeof SuppliesRoute
  '/tasks': typeof TasksRoute
  '/visitors': typeof VisitorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/leave': typeof LeaveRoute
  '/meetings': typeof MeetingsRoute
  '/more': typeof MoreRoute
  '/reports': typeof ReportsRoute
  '/supplies': typeof SuppliesRoute
  '/tasks': typeof TasksRoute
  '/visitors': typeof VisitorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/contacts'
    | '/documents'
    | '/leave'
    | '/meetings'
    | '/more'
    | '/reports'
    | '/supplies'
    | '/tasks'
    | '/visitors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/contacts'
    | '/documents'
    | '/leave'
    | '/meetings'
    | '/more'
    | '/reports'
    | '/supplies'
    | '/tasks'
    | '/visitors'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assistant'
    | '/contacts'
    | '/documents'
    | '/leave'
    | '/meetings'
    | '/more'
    | '/reports'
    | '/supplies'
    | '/tasks'
    | '/visitors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  ContactsRoute: typeof ContactsRoute
  DocumentsRoute: typeof DocumentsRoute
  LeaveRoute: typeof LeaveRoute
  MeetingsRoute: typeof MeetingsRoute
  MoreRoute: typeof MoreRoute
  ReportsRoute: typeof ReportsRoute
  SuppliesRoute: typeof SuppliesRoute
  TasksRoute: typeof TasksRoute
  VisitorsRoute: typeof VisitorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies': {
      id: '/supplies'
      path: '/supplies'
      fullPath: '/supplies'
      preLoaderRoute: typeof SuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  ContactsRoute: ContactsRoute,
  DocumentsRoute: DocumentsRoute,
  LeaveRoute: LeaveRoute,
  MeetingsRoute: MeetingsRoute,
  MoreRoute: MoreRoute,
  ReportsRoute: ReportsRoute,
  SuppliesRoute: SuppliesRoute,
  TasksRoute: TasksRoute,
  VisitorsRoute: VisitorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
